order.params.a=787
order.params.b=919
spring.datasource.url=jdbc:h2:mem:orders-db
spring.h2.console.enabled=true
logging.level.net.anas.order_service.services.CustomerRestClientService=debug
logging.level.net.anas.order_service.services.InventoryRestClientService=debug
feigh.client.config.default.loggerLevel=full